// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptionsDev {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDUvXYY9QVLEa_MRMxJ4F0N81bHQQmuwA',
    appId: '1:440550480887:android:caf95523eaa553a77aacf2',
    messagingSenderId: '440550480887',
    projectId: 'hafizh-dev',
    storageBucket: 'hafizh-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUA1HBFqBIy8CXh1UCcEWEaaWr2sDs16I',
    appId: '1:440550480887:ios:98769705f74270307aacf2',
    messagingSenderId: '440550480887',
    projectId: 'hafizh-dev',
    storageBucket: 'hafizh-dev.appspot.com',
    iosClientId:
        '440550480887-qmc28r0oen7fp209hm4o88j8v7ikjbdv.apps.googleusercontent.com',
    iosBundleId: 'com.sixmavericks.hafizh.dev',
  );
}
